module.exports = products = [
    {
      id: 1,
      name: "Pomegranate",
      retail_price: 3.2,
      wholesale_price: 2.9,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/nar.jpg",
      date: "2023-09-10",
      category: "fruits",
    },
    {
      id: 2,
      name: "Tangerine",
      retail_price: 3.75,
      wholesale_price: 3.55,
      image_url: "https://rofruit-api.onrender.com/uploads/naringi.jpg",
      date: "2023-09-12",
      category: "fruits",
    },
    {
      id: 3,
      name: "Grapes",
      retail_price: 2.65,
      wholesale_price: 2.45,
      discount: 5,
      image_url: "https://rofruit-api.onrender.com/uploads/uzum.jpg",
      date: "2023-09-08",
      category: "fruits",
    },
    {
      id: 4,
      name: "Cranberry",
      retail_price: 1.95,
      wholesale_price: 1.65,
      image_url: "https://rofruit-api.onrender.com/uploads/zogal.jpg",
      date: "2023-09-14",
      category: "fruits",
    },
    {
      id: 5,
      name: "Grape Black",
      retail_price: 1.59,
      wholesale_price: 1.29,
      image_url: "https://rofruit-api.onrender.com/uploads/uzum_qara.jpg",
      date: "2023-09-07",
      category: "fruits",
    },
    {
      id: 6,
      name: "Plum",
      retail_price: 2.55,
      wholesale_price: 2.25,
      discount: 8,
      image_url: "https://rofruit-api.onrender.com/uploads/gavali.jpg",
      date: "2023-09-09",
      category: "fruits",
    },
    {
      id: 7,
      name: "Pear",
      retail_price: 1.65,
      wholesale_price: 1.35,
      discount: 4,
      image_url: "https://rofruit-api.onrender.com/uploads/armud.jpg",
      date: "2023-09-06",
      category: "fruits",
    },
    {
      id: 8,
      name: "Peach",
      retail_price: 1.75,
      wholesale_price: 1.45,
      image_url: "https://rofruit-api.onrender.com/uploads/saftali.jpg",
      date: "2023-09-13",
      category: "fruits",
    },
    {
      id: 9,
      name: "Orange",
      retail_price: 3.55,
      wholesale_price: 3.25,
      discount: 12,
      image_url: "https://rofruit-api.onrender.com/uploads/portagal.jpg",
      date: "2023-09-11",
      category: "fruits",
    },
    {
      id: 10,
      name: "Banana",
      retail_price: 2.35,
      wholesale_price: 2.15,
      image_url: "https://rofruit-api.onrender.com/uploads/banan.jpg",
      date: "2023-09-05",
      category: "fruits",
    },
    {
      id: 11,
      name: "Apple",
      retail_price: 1.45,
      wholesale_price: 1.15,
      image_url: "https://rofruit-api.onrender.com/uploads/alma.jpg",
      date: "2023-09-15",
      category: "fruits",
    },
    {
      id: 12,
      name: "Grapefruit",
      retail_price: 3.25,
      wholesale_price: 2.95,
      discount: 14,
      image_url: "https://rofruit-api.onrender.com/uploads/qreypfrut.jpg",
      date: "2023-09-04",
      category: "fruits",
    },
    {
      id: 13,
      name: "Kiwi",
      retail_price: 3.3,
      wholesale_price: 3,
      discount: 5,
      image_url: "https://rofruit-api.onrender.com/uploads/kivi.jpg",
      date: "2023-09-03",
      category: "fruits",
    },
    {
      id: 14,
      name: "Blackthorn",
      retail_price: 2.55,
      wholesale_price: 2.25,
      image_url: "https://rofruit-api.onrender.com/uploads/goyem.jpg",
      date: "2023-09-02",
      category: "fruits",
    },
    {
      id: 15,
      name: "Green apple",
      retail_price: 1.65,
      wholesale_price: 1.35,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/alma_yasil.jpg",
      date: "2023-09-01",
      category: "fruits",
    },
    {
      id: 16,
      name: "Tomato",
      retail_price: 1.05,
      wholesale_price: 0.85,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/pomidor.jpg",
      date: "2023-09-20",
      category: "vegetables",
    },
    {
      id: 17,
      name: "Garlic",
      retail_price: 3.3,
      wholesale_price: 3.1,
      discount: 14,
      image_url: "https://rofruit-api.onrender.com/uploads/sarimsaq.jpg",
      date: "2023-09-19",
      category: "vegetables",
    },
    {
      id: 18,
      name: "Pumpkin",
      retail_price: 0.55,
      wholesale_price: 0.25,
      image_url: "https://rofruit-api.onrender.com/uploads/balqabaq.png",
      date: "2023-09-18",
      category: "vegetables",
    },
    {
      id: 19,
      name: "Pepper Hot",
      retail_price: 1.59,
      wholesale_price: 1.39,
      discount: 15,
      image_url: "https://rofruit-api.onrender.com/uploads/biber_aci.jpg",
      date: "2023-09-17",
      category: "vegetables",
    },
    {
      id: 20,
      name: "Melon",
      retail_price: 0.95,
      wholesale_price: 0.75,
      image_url: "https://rofruit-api.onrender.com/uploads/yemis.jpg",
      date: "2023-09-16",
      category: "vegetables",
    },
    {
      id: 21,
      name: "Potato",
      retail_price: 0.89,
      wholesale_price: 0.59,
      image_url: "https://rofruit-api.onrender.com/uploads/kartof.jpg",
      date: "2023-09-25",
      category: "vegetables",
    },
    {
      id: 22,
      name: "Pepper",
      retail_price: 1.65,
      wholesale_price: 1.35,
      discount: 12,
      image_url: "https://rofruit-api.onrender.com/uploads/biber.jpeg",
      date: "2023-09-24",
      category: "vegetables",
    },
    {
      id: 23,
      name: "Beans",
      retail_price: 3.05,
      wholesale_price: 2.75,
      discount: 6,
      image_url: "https://rofruit-api.onrender.com/uploads/lobya.jpeg",
      date: "2023-09-23",
      category: "vegetables",
    },
    {
      id: 24,
      name: "Cucumber",
      retail_price: 0.79,
      wholesale_price: 0.49,
      image_url: "https://rofruit-api.onrender.com/uploads/xiyar.jpg",
      date: "2023-09-22",
      category: "vegetables",
    },
    {
      id: 25,
      name: "Onion",
      retail_price: 3.95,
      wholesale_price: 3.65,
      image_url: "https://rofruit-api.onrender.com/uploads/sogan.jpg",
      date: "2023-09-21",
      category: "vegetables",
    },
    {
      id: 26,
      name: "Watermelon",
      retail_price: 0.69,
      wholesale_price: 0.39,
      discount: 9,
      image_url: "https://rofruit-api.onrender.com/uploads/qarpiz.jpg",
      date: "2023-09-20",
      category: "vegetables",
    },
    {
      id: 27,
      name: "Aubergine",
      retail_price: 1.19,
      wholesale_price: 0.89,
      image_url: "https://rofruit-api.onrender.com/uploads/badimcan.jpeg",
      date: "2023-09-19",
      category: "vegetables",
    },
    {
      id: 28,
      name: "Carrot",
      retail_price: 1.1,
      wholesale_price: 0.8,
      image_url: "https://rofruit-api.onrender.com/uploads/kok.jpg",
      date: "2023-09-18",
      category: "vegetables",
    },
    {
      id: 29,
      name: "Cabbage",
      retail_price: 0.65,
      wholesale_price: 0.45,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/kelem.png",
      date: "2023-09-17",
      category: "vegetables",
    },
    {
      id: 30,
      name: "Aubergine Round",
      retail_price: 1.15,
      wholesale_price: 0.85,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/badimcan_yumru.jpg",
      date: "2023-09-16",
      category: "vegetables",
    },
    {
      id: 31,
      name: "Ginger",
      retail_price: 11.9,
      wholesale_price: 11.6,
      image_url: "https://rofruit-api.onrender.com/uploads/zencefil.png",
      date: "2023-09-15",
      category: "vegetables",
    },
    {
      id: 32,
      name: "Broccoli",
      retail_price: 5.7,
      wholesale_price: 5.5,
      discount: 11,
      image_url: "https://rofruit-api.onrender.com/uploads/brokoli.jpg",
      date: "2023-09-14",
      category: "vegetables",
    },
    {
      id: 33,
      name: "Mushroom",
      retail_price: 3.99,
      wholesale_price: 3.69,
      image_url: "https://rofruit-api.onrender.com/uploads/gobelek.jpg",
      date: "2023-09-13",
      category: "vegetables",
    },
    {
      id: 34,
      name: "Beet",
      retail_price: 0.95,
      wholesale_price: 0.65,
      image_url: "https://rofruit-api.onrender.com/uploads/cugundur.jpg",
      date: "2023-09-12",
      category: "vegetables",
    },
    {
      id: 35,
      name: "Onion Red",
      retail_price: 1.09,
      wholesale_price: 0.79,
      discount: 18,
      image_url: "https://rofruit-api.onrender.com/uploads/sogan_qirmizi.png",
      date: "2023-09-11",
      category: "vegetables",
    },
    {
      id: 36,
      name: "White cherry",
      retail_price: 1.4,
      wholesale_price: 0.5,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/ag_gilas.webp",
      date: "2023-10-01",
      category: "berries",
    },
    {
      id: 37,
      name: "Black fig",
      retail_price: 2.6,
      wholesale_price: 2.0,
      image_url: "https://rofruit-api.onrender.com/uploads/qara_encir.webp",
      date: "2023-09-11",
      category: "berries",
    },
    {
      id: 38,
      name: "Cherry",
      retail_price: 3.5,
      wholesale_price: 3.2,
      image_url: "https://rofruit-api.onrender.com/uploads/alca.webp",
      date: "2023-09-19",
      category: "berries",
    },
    {
      id: 39,
      name: "Strawberry",
      retail_price: 1.5,
      wholesale_price: 1.3,
      discount: 20,
      image_url: "https://rofruit-api.onrender.com/uploads/ciyelek.webp",
      date: "2023-08-19",
      category: "berries",
    },
    {
      id: 40,
      name: "Black currant",
      retail_price: 4.5,
      wholesale_price: 4.2,
      image_url: "https://rofruit-api.onrender.com/uploads/qara_qaragat.webp",
      date: "2023-09-22",
      category: "berries",
    },
    {
      id: 41,
      name: "Raspberry",
      retail_price: 3.0,
      wholesale_price: 2.8,
      image_url: "https://rofruit-api.onrender.com/uploads/moruq.webp",
      date: "2023-09-27",
      category: "berries",
    },
    {
      id: 42,
      name: "Blackberry",
      retail_price: 3.0,
      wholesale_price: 2.8,
      discount: 15,
      image_url: "https://rofruit-api.onrender.com/uploads/boyurtken.webp",
      date: "2023-09-18",
      category: "berries",
    },
    {
      id: 43,
      name: "Cranberry",
      retail_price: 3.3,
      wholesale_price: 3.1,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/zogal.webp",
      date: "2023-09-30",
      category: "berries",
    },
    {
      id: 44,
      name: "Red currant",
      retail_price: 4.8,
      wholesale_price: 4.4,
      image_url: "https://rofruit-api.onrender.com/uploads/qirmizi_qaragat.webp",
      date: "2023-09-22",
      category: "berries",
    },
    {
      id: 45,
      name: "gooseberry",
      retail_price: 3.9,
      wholesale_price: 3.7,
      image_url: "https://rofruit-api.onrender.com/uploads/motmotu.webp",
      date: "2023-09-28",
      category: "berries",
    },
    {
      id: 46,
      name: "Hawthorn",
      retail_price: 3.1,
      wholesale_price: 2.9,
      image_url: "https://rofruit-api.onrender.com/uploads/yemisan.jpg",
      date: "2023-09-05",
      category: "berries",
    },
    {
      id: 47,
      name: "Purified chestnut",
      retail_price: 12.3,
      wholesale_price: 11.5,
      image_url: "https://rofruit-api.onrender.com/uploads/temiz_sabalid.webp",
      date: "2023-09-15",
      category: "dry-fruits",
    },
    {
      id: 48,
      name: "Dried apple",
      retail_price: 9.3,
      wholesale_price: 9.0,
      discount: 10,
      image_url: "https://rofruit-api.onrender.com/uploads/alma_qurusu.webp",
      date: "2023-09-24",
      category: "dry-fruits",
    },
    {
      id: 49,
      name: "Dried strawberry",
      retail_price: 10.5,
      wholesale_price: 10.2,
      image_url: "https://rofruit-api.onrender.com/uploads/ciyelek_qurusu.webp",
      date: "2023-09-25",
      category: "dry-fruits",
    },
    {
      id: 50,
      name: "Dried mango",
      retail_price: 14.78,
      wholesale_price: 14.55,
      discount: 20,
      image_url: "https://rofruit-api.onrender.com/uploads/manqo_qurusu.webp",
      date: "2023-09-01",
      category: "dry-fruits",
    },
    {
      id: 51,
      name: "Dried cherry",
      retail_price: 11.11,
      wholesale_price: 11.01,
      image_url: "https://rofruit-api.onrender.com/uploads/albali_qurusu.webp",
      date: "2023-09-19",
      category: "dry-fruits",
    },
    {
      id: 52,
      name: "Dried figs",
      retail_price: 9.55,
      wholesale_price: 9.15,
      image_url: "https://rofruit-api.onrender.com/uploads/quru_encir.webp",
      date: "2023-09-09",
      category: "dry-fruits",
    },
    {
      id: 53,
      name: "Dried innab",
      retail_price: 10.38,
      wholesale_price: 10.08,
      image_url: "https://rofruit-api.onrender.com/uploads/qurudulmus_innab.webp",
      date: "2023-09-27",
      category: "dry-fruits",
    },
    {
      id: 54,
      name: "Dried apricots",
      retail_price: 8.88,
      wholesale_price: 8.22,
      image_url: "https://rofruit-api.onrender.com/uploads/quru_erik.webp",
      date: "2023-10-02",
      category: "dry-fruits",
    },
    {
      id: 55,
      name: "Prunes",
      retail_price: 9.58,
      wholesale_price: 9.32,
      image_url: "https://rofruit-api.onrender.com/uploads/quru_gavali.webp",
      date: "2023-10-01",
      category: "dry-fruits",
    },
    {
      id: 56,
      name: "Dried mulberry",
      retail_price: 5.58,
      wholesale_price: 5.15,
      image_url: "https://rofruit-api.onrender.com/uploads/quru_tut.webp",
      date: "2023-09-02",
      category: "dry-fruits",
    },
    {
      id: 57,
      name: "Albukhara",
      retail_price: 7.52,
      wholesale_price: 7.23,
      image_url: "https://rofruit-api.onrender.com/uploads/albuxara.webp",
      date: "2023-09-11",
      category: "dry-fruits",
    },
    {
      id: 58,
      name: "Yellow raisins",
      retail_price: 13.55,
      wholesale_price: 13.33,
      discount: 18,
      image_url: "https://rofruit-api.onrender.com/uploads/sari_kismis.webp",
      date: "2023-09-21",
      category: "dry-fruits",
    },
    {
      id: 59,
      name: "Black raisins",
      retail_price: 12.55,
      wholesale_price: 12.33,
      discount: 19,
      image_url: "https://rofruit-api.onrender.com/uploads/qara_kismis.webp",
      date: "2023-09-21",
      category: "dry-fruits",
    },
    {
      id: 60,
      name: "Dried kiwi",
      retail_price: 14.35,
      wholesale_price: 13.82,
      discount: 12,
      image_url: "https://rofruit-api.onrender.com/uploads/quru_kivi.webp",
      date: "2023-09-21",
      category: "dry-fruits",
    },
    {
      id: 61,
      name: "Pineapple",
      retail_price: 6.65,
      wholesale_price: 6.36,
      discount: 20,
      image_url: "https://rofruit-api.onrender.com/uploads/ananas.webp",
      date: "2023-09-21",
      category: "exotic",
    },
    {
      id: 62,
      name: "Avocado",
      retail_price: 6.95,
      wholesale_price: 6.66,
      image_url: "https://rofruit-api.onrender.com/uploads/avokado.webp",
      date: "2023-09-10",
      category: "exotic",
    },
    {
      id: 63,
      name: "Passion fruit",
      retail_price: 18.43,
      wholesale_price: 18.23,
      image_url: "https://rofruit-api.onrender.com/uploads/marakuya.webp",
      date: "2023-09-03",
      category: "exotic",
    },
    {
      id: 64,
      name: "Granadilla",
      retail_price: 10.73,
      wholesale_price: 10.12,
      discount: 16,
      image_url: "https://rofruit-api.onrender.com/uploads/qranadilla.webp",
      date: "2023-10-02",
      category: "exotic",
    },
    {
      id: 65,
      name: "Carambola",
      retail_price: 6.43,
      wholesale_price: 6.12,
      image_url: "https://rofruit-api.onrender.com/uploads/karambola.webp",
      date: "2023-10-05",
      category: "exotic",
    },
    {
      id: 66,
      name: "Mango",
      retail_price: 8.29,
      wholesale_price: 7.89,
      image_url: "https://rofruit-api.onrender.com/uploads/manqo.webp",
      date: "2023-10-01",
      category: "exotic",
    },
    {
      id: 67,
      name: "Lyme",
      retail_price: 8.1,
      wholesale_price: 7.59,
      discount: 15,
      image_url: "https://rofruit-api.onrender.com/uploads/laym.webp",
      date: "2023-09-30",
      category: "exotic",
    },
    {
      id: 68,
      name: "Tamarind",
      retail_price: 19.99,
      wholesale_price: 19.49,
      image_url: "https://rofruit-api.onrender.com/uploads/tamarind.webp",
      date: "2023-10-04",
      category: "exotic",
    },
    {
      id: 69,
      name: "Feijoa",
      retail_price: 4.59,
      wholesale_price: 4.29,
      image_url: "https://rofruit-api.onrender.com/uploads/feyxoa.webp",
      date: "2023-09-24",
      category: "exotic",
    },
    {
      id: 70,
      name: "Coconut",
      retail_price: 8.55,
      wholesale_price: 8.05,
      image_url: "https://rofruit-api.onrender.com/uploads/kokos.webp",
      date: "2023-09-14",
      category: "exotic",
    },
    {
      id: 71,
      name: "Walnut",
      retail_price: 15.55,
      wholesale_price: 15.05,
      image_url: "https://rofruit-api.onrender.com/uploads/qoz.webp",
      date: "2023-09-16",
      category: "nuts",
    },
    {
      id: 72,
      name: "Pumpkin seeds",
      retail_price: 12.25,
      wholesale_price: 11.95,
      discount: 18,
      image_url: "https://rofruit-api.onrender.com/uploads/balqabaq_tumu.webp",
      date: "2023-09-05",
      category: "nuts",
    },
    {
      id: 73,
      name: "Hazel",
      retail_price: 14.15,
      wholesale_price: 13.65,
      image_url: "https://rofruit-api.onrender.com/uploads/findiq.webp",
      date: "2023-09-25",
      category: "nuts",
    },
    {
      id: 74,
      name: "Pistachio",
      retail_price: 11.88,
      wholesale_price: 11.66,
      discount: 8,
      image_url: "https://rofruit-api.onrender.com/uploads/puste.webp",
      date: "2023-09-29",
      category: "nuts",
    },
    {
      id: 75,
      name: "Peanut",
      retail_price: 10.15,
      wholesale_price: 9.85,
      image_url: "https://rofruit-api.onrender.com/uploads/fistiq.webp",
      date: "2023-09-22",
      category: "nuts",
    },
    {
      id: 76,
      name: "Almond",
      retail_price: 15.15,
      wholesale_price: 14.68,
      image_url: "https://rofruit-api.onrender.com/uploads/badam.webp",
      date: "2023-10-01",
      category: "nuts",
    },
    {
      id: 77,
      name: "Cashew",
      retail_price: 13.34,
      wholesale_price: 13.04,
      discount: 12,
      image_url: "https://rofruit-api.onrender.com/uploads/kesyu.webp",
      date: "2023-09-14",
      category: "nuts",
    },
    {
      id: 78,
      name: "Sesame",
      retail_price: 8.54,
      wholesale_price: 8.02,
      discount: 20,
      image_url: "https://rofruit-api.onrender.com/uploads/kuncut.webp",
      date: "2023-10-04",
      category: "nuts",
    },
    {
      id: 79,
      name: "Chestnut",
      retail_price: 14.29,
      wholesale_price: 13.99,
      image_url: "https://rofruit-api.onrender.com/uploads/sabalid.webp",
      date: "2023-09-29",
      category: "nuts",
    },
    {
      id: 80,
      name: "Roasted corn",
      retail_price: 5.29,
      wholesale_price: 5.09,
      image_url: "https://rofruit-api.onrender.com/uploads/qovrulmus_qargidali.webp",
      date: "2023-09-21",
      category: "nuts",
    },
  ];